### ISSUE TITLE
android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@a59d688 -- permission denied for window type 2038

### ISSUE THREAD

**Issue by piotrek-chmielowski** [sockeqwe/debugoverlay#6]
In my `Fragment` I have the following code:

```
    @Override
    public void onResume() {
        super.onResume();
        DebugOverlay.with(getContext()).log("Hello");
    }
```

In the AndroidManifest.xml:
`<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>`

And I'm getting following error:
```
                  android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@a59d688 -- permission denied for window type 2038
                      at android.view.ViewRootImpl.setView(ViewRootImpl.java:789)
                      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
                      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                      at com.hannesdorfmann.debugoverlay.DebugOverlayView.<init>(DebugOverlayView.java:80)
                      at com.hannesdorfmann.debugoverlay.DebugOverlayService.logMsg(DebugOverlayService.java:36)
                      at com.hannesdorfmann.debugoverlay.DebugOverlay$MessageDispatcher.dispatch(DebugOverlay.java:118)
                      at com.hannesdorfmann.debugoverlay.DebugOverlay$MessageDispatcher.setService(DebugOverlay.java:87)
                      at com.hannesdorfmann.debugoverlay.DebugOverlay$1.onServiceConnected(DebugOverlay.java:27)
                      at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1652)
                      at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1681)
                      at android.os.Handler.handleCallback(Handler.java:790)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Android version: Oreo.
Am I doing something wrong or is it a bug?

**Comment by sockeqwe** [comment]
Since Android 7 you explicitly have to grant a permission "Draw over other apps" for apps not installed over play store (which is the case for debug builds, right?)

To grant permission take a look here:
https://lastpass.com/support.php?cmd=showfaq&id=9932

**Comment by javierdiaziut** [comment]
I am facing the same problem, how did you solved it? 

Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@7a40cfc -- permission denied for window type 2038
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:817)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.app.Dialog.show(Dialog.java:330)
        at com.app.health.daytoday_android.framework.NotificationService.launchDialog(NotificationService.kt:527)
        at com.app.health.daytoday_android.framework.NotificationService.onStartCommand(NotificationService.kt:101)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3565)
        at android.app.ActivityThread.-wrap21(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1742) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6626) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by 0xSG** [comment]
@javierdiaziut, even I am getting the same problem. Did you get the solution now?

**Comment by 0xSG** [comment]
@piotrek-chmielowski @javierdiaziut I got the solution:
https://gist.github.com/0xpulsar/0c072eba142bc3ee72ba627824a2ce25
